spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fireant
    username: dbuser
    password: dbuser
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
    
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

logging:
  level:
    root: info

server:
  port: 8181

